namespace SpriteKind {
    export const échelle = SpriteKind.create()
    export const kong = SpriteKind.create()
    export const peacht = SpriteKind.create()
    export const tonneau = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        mySprite.vy = -150
    }
})
info.onCountdownEnd(function () {
    info.changeLifeBy(-1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.peacht, function (sprite, otherSprite) {
    game.setGameOverMessage(true, "Velkommen til time")
    game.setGameOverEffect(true, effects.starField)
    game.gameOver(true)
})
info.onLifeZero(function () {
    game.gameOver(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    mySprite.setFlag(SpriteFlag.GhostThroughSprites, true)
    info.startCountdown(0.5)
    mySprite.setFlag(SpriteFlag.GhostThroughSprites, false)
})
let mySprite5: Sprite = null
let mySprite2: Sprite = null
let mySprite: Sprite = null
scene.setBackgroundColor(1)
tiles.setCurrentTilemap(tilemap`level7`)
mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f e e 2 2 2 2 2 2 e f f . . 
    . f f e 2 f f f f f f 2 e f f . 
    . f f f f f e e e e f f f f f . 
    . . f e f b f 4 4 f b f e f . . 
    . . f e 4 1 f d d f 1 4 e f . . 
    . . e f e 4 d d d d 4 e f . . . 
    . . e 4 d d e 2 2 2 2 f e f . . 
    . . . e d d e 2 2 2 2 f 4 e . . 
    . . . . e e f 5 5 4 4 f . . . . 
    . . . . . f f f f f f f . . . . 
    . . . . . . . . . f f f . . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 0)
mySprite.setStayInScreen(false)
mySprite.ay = 300
mySprite.setPosition(380, 600)
info.setLife(5)
info.startCountdown(100)
scene.cameraFollowSprite(mySprite)
let Astrid = sprites.create(img`
    .........................
    .........................
    .........................
    ........55555............
    .......559d955...........
    .......5ddddd5...........
    ......55dd1dd5...........
    ......555.d.555..........
    .....55.2ddd2.55.........
    .......2222222...........
    ......222222222..........
    ......222222222..........
    ......222222222..........
    ......222222222..........
    ......222222222..........
    ......222222222..........
    ......222222222..........
    ......222222222..........
    ......222222222..........
    ........88.88............
    ........88.88............
    ......8888.8888..........
    ......8888.8888..........
    .........................
    .........................
    `, SpriteKind.peacht)
Astrid.setPosition(340, 89)
forever(function () {
    for (let index = 0; index < 9999; index++) {
        pause(3000)
        mySprite2 = sprites.create(img`
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ........ff..........
            .......f..f....f....
            .......f..f....f....
            ........ff.....f....
            .....222.......f....
            .....222....ffff....
            .....2f2....ffff....
            .....22222222222....
            ....222222222222....
            ...2.22222222222....
            ..2..fff.....fff....
            .2...f.f.....f.f....
            222..fff.....fff....
            `, SpriteKind.Enemy)
        tiles.placeOnRandomTile(mySprite2, assets.tile`myTile8`)
        mySprite2.setVelocity(-50, 0)
        mySprite2.ay = 350
        mySprite2.setBounceOnWall(true)
    }
})
forever(function () {
    for (let index = 0; index < 9999; index++) {
        pause(3000)
        mySprite5 = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . a a a a a . . . . . . . . 
            . . . a a a d d . . . . . . . . 
            . . . a a d d a . . . . . . . . 
            . . . a d d d d . . . . . . . . 
            . . . a d d d 2 . . . . . . . . 
            . . . . f f f f . . . . . . . . 
            . 5 5 5 f f a f . . . . . . . . 
            . 5 5 5 f f a f . . . . . . . . 
            . 5 5 5 f f a f . . . . . . . . 
            . 5 5 5 f f f f . . . . . . . . 
            . . . . a a a a . . . . . . . . 
            . . . . a . . a . . . . . . . . 
            . . . . a . . a . . . . . . . . 
            . . . . a . . a . . . . . . . . 
            `, SpriteKind.Enemy)
        tiles.placeOnRandomTile(mySprite5, assets.tile`myTile8`)
        mySprite5.setVelocity(50, 0)
        mySprite5.ay = 500
    }
})
